#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

# Libs and deps variables
export LD_LIBRARY_PATH="$HERE/atom":"$LD_LIBRARY_PATH"

# from .desktop
#export ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false

export PATH="$HERE/atom":"$PATH"
# Detect APM (Atom Package Manager)
export PATH="$HERE/atom/resources/app/apm/bin":"$PATH"

MAIN="$HERE/atom/atom"
"$MAIN" "$@" | cat
